text_extensions: [
  'bib', 'php', 'rb', 'js',
  'css', 'less', 'sass', 'scss',
  'erb', 'haml',
  'txt', 'markdown', 'md',
  'htm', 'html', 'xhtml', 'xml',
  'feed' ]

# output_dir: output
output_dir: /Users/damien/Sites/nanoc
# enable_output_diff: false
# index_filenames: [ 'index.html' ]

data_sources:
  - { type: filesystem_unified, items_root: /, layouts_root: / }

deploy:
  local:
    kind: rsync
    dst: localhost:/Users/damien/Sites/website-nanoc
    options: [ --rsh=ssh, --archive, --delete-after, --verbose, --progress, --compress ]
  public:
    kind: rsync
    dst: ryu.zarb.org:/home/users/cdlm/vhosts/people.untyped.org/docroot/damien.pollet
    options: [ --rsh=ssh, --archive, --delete-after, --verbose, --progress, --compress ]

tag_base_url: /notes/tags/
#http://people.untyped.org/damien.pollet

# default and global metadata
default_info:
  author: Damien Pollet
  author_url: http://people.untyped.org/damien.pollet
  analytics: 'UA-718463-2'
  site_lang: en
  header_title: Damien Pollet
  header_url: /
  header_slogan: >
    Assistant professor,
    <a href="http://www.univ-lille1.fr">university of Lille 1, France</a><br/>
    <em>object-oriented software (re)engineering &amp; language design</em>
  description: >
    Website of Damien Pollet, Ph.D
  keywords: >
    software engineering,
    programming languages,
    reengineering,
    visualisation,
    virtual machines,
    object-oriented
  header_menu:
    - /publications/
    - /research/
    - /teaching/
    - /software/
    - /curriculum/
    - /contact/
    - /notes/

