text_extensions: [
  'bib', 'php', 'rb', 'js',
  'css', 'less', 'sass', 'scss',
  'erb', 'haml',
  'txt', 'markdown', 'md',
  'htm', 'html', 'xhtml', 'xml',
  'feed' ]
hidden_extensions: [
  'png', 'gif', 'jpg', 'jpeg',
  'js', 'coffee',
  'css', 'scss', 'sass', 'less' ]

data_sources:
  - { type: filesystem_unified, items_root: /, layouts_root: /, allow_periods_in_identifiers: true }

deploy:
  default:
    kind: rsync
    dst: staging/damien.pollet
    options: &RSYNCOPTS [ --rsh=ssh, --archive, --delete-after, --verbose, --compress ]
  public:
    kind: rsync
    dst: ryu.zarb.org:/home/users/cdlm/vhosts/people.untyped.org/docroot/damien.pollet
    options: *RSYNCOPTS

base_url: &BASE http://people.untyped.org/damien.pollet
author_uri: *BASE

# default and global metadata
default_info:
  author_name: &ME Damien Pollet
  analytics: 'UA-718463-2'
  site_lang: en
  header_title: *ME
  header_url: /
  header_slogan: >
    Assistant professor,
    <a href="http://www.univ-lille1.fr">university of Lille 1, France</a><br/>
    <em>object-oriented software (re)engineering &amp; language design</em>
  description: >
    Website of Damien Pollet, Ph.D
  keywords: >
    software engineering,
    programming languages,
    reengineering,
    visualisation,
    virtual machines,
    object-oriented
  header_menu:
    - /publications/
    - /research/
    - /teaching/
    - /software/
    - /curriculum/
    - /contact/
    - /notes/

